class RepositoryError(RuntimeError): ...
class IntegrationError(RuntimeError):
    def __init__(self, service: str, msg: str): super().__init__(f"[{service}] {msg}")

class SaleCreationError(RuntimeError): ...
class DuplicateSaleError(RuntimeError): ...
class InsufficientStockError(RuntimeError): ...